# Generated by Django 6.0.2 on 2026-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0005_alter_waterbottle_current_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
